version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8010:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./timeline/public:/var/www/timeline/public
    depends_on:
      - php

  php:
    container_name: php-laravel
    build: ./docker/php
    volumes:
      - ./:/var/www/
    environment:
      - NODE_ENV=${NODE_ENV}

  db:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3306:3306
    environment: 
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TZ}
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8811:80
    depends_on:
      - db
  sseserver:
    image: sse-server:1.0
    ports: 
      - 3000:3000
    environment:
      - API_KEY=${API_KEY}
      - API_KEY_SECRET=${API_KEY_SECRET}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - BEARE_TOKEN=${BEARE_TOKEN}
      - TRACK_WORDS=${TRACK_WORDS}
      - APP_SERVER_PORT=${APP_SERVER_PORT}
      - WEB_SERVER_URL=${WEB_SERVER_URL}
      - WEB_SERVER_PORT=${WEB_SERVER_PORT}
volumes: 
  db-store: